# Liste des fournisseurs à utiliser lors de la construction
providers = ["...", "node"]
# Variables d'environnement à définir lors de la construction
[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

NIXPACKS_NODE_VERSION= "20"
